{% set version = "5.26.1" %}    # [unix]
{% set version = "5.26.0.2" %}  # [win]


package:
  name: perl
  version: {{ version }}

source:
  fn:   perl-{{ version }}.tar.gz                                                                           # [unix]
  url:  http://www.cpan.org/src/5.0/perl-{{ version }}.tar.gz                                               # [unix]
  sha1: 74a0822429508d593513a0dfd6f51a907bad68d0                                                            # [unix]

  fn:   strawberry-perl-{{ version }}-32bit-portable.zip                                                    # [win]
  url:  http://strawberryperl.com/download/{{version}}/strawberry-perl-{{version}}-32bit-portable.zip       # [win]
  sha1: c2dd24fa0103d8db6553b744e29f196ad40cfe4c                                                            # [win]

  patches: 
    - patch-perl-unix-test.diff                                                                             # [unix]

build:
  number: 0

test:
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic License
  license_family: Other
  license: Perl
  summary: "The Perl programming language interpreter."


extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
