schema_version: 1

context:
  unix_version: "5.32.1"
  win_version: "5.32.1.1"
  major_minor_version: "5.32"

package:
  name: perl
  version: ${{ win_version if win else unix_version }}

source:
  - if: unix
    then:
      url: http://www.cpan.org/src/5.0/perl-${{ unix_version }}.tar.xz
      sha256: 57cc47c735c8300a8ce2fa0643507b44c4ae59012bfdad0121313db639e02309
      patches:
        - 0001-Use-userelocatableinc-together-with-useshrplib.patch
        - 0002-Disable-direct-invocation-of-linker-if-LD-is-set.patch
  - if: win64
    then:
      url: https://strawberryperl.com/download/${{ win_version }}/strawberry-perl-${{ win_version }}-64bit-portable.zip
      sha256: 692646105b0f5e058198a852dc52a48f1cebcaf676d63bbdeae12f4eaee9bf5c
  - if: win32
    then:
      url: https://strawberryperl.com/download/${{ win_version }}/strawberry-perl-${{ win_version }}-32bit-portable.zip
      sha256: d9c5711d12573a0f6d977792caa58364b1d46217521ae5c25cf5cc378a7c23c0

build:
  number: 8
  string: ${{ build_number }}_h${{ hash }}_${{ 'strawberry' if target_platform == 'win-64' or target_platform == 'win-32' else 'perl5' }}
  script: build

requirements:
  build:
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - make
    - if: win
      then: m2-base
  host:
    - if: linux
      then: libxcrypt
  run_exports:
    weak:
      - perl >=${{ win_version if win else unix_version }},<5.33.0a0 *_${{ 'strawberry' if win else 'perl5' }}
    noarch:
      - perl >=${{ win_version if win else unix_version }},<6.0a0 *_${{ 'strawberry' if win else 'perl5' }}

tests:
  - package_contents:
      bin:
        - perl
  - if: unix
    then:
      requirements:
        build:
          - ${{ stdlib('c') }}
      script:
        - if: build_platform != target_platform
          then: export QEMU_LD_PREFIX="$CONDA_PREFIX/${target_platform#linux-}-conda-linux-gnu/sysroot"
        - perl --help
        - >-
          "$PREFIX/bin/perl" -V:cf_by | grep -qF "'conda'"
        - >-
          "$PREFIX/bin/perl" -V:cf_email | grep -qF "'conda'"
        - >-
          "$PREFIX/bin/perl" -V:perladmin | grep -qF "'conda'"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/site_perl"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/vendor_perl"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/core_perl"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/${{ major_minor_version }}/site_perl"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/${{ major_minor_version }}/vendor_perl"
        - >-
          "$PREFIX/bin/perl" -e 'print "$_\n" for @INC' | grep -qxF "$PREFIX/lib/perl5/${{ major_minor_version }}/core_perl"
  # Conda replaces backslashes with forward slashes during prefix replacement,
  # leaving mixed separators in Config.pm and Config_heavy.pl. Perl supports it.
  - if: win
    then:
      script:
        - perl --help
        - perl -V:privlib | findstr "/C:%PREFIX:\=/%\Library\lib"
        - perl -V:archlib | findstr "/C:%PREFIX:\=/%\Library\lib"
        - perl -V:sitelib | findstr "/C:%PREFIX:\=/%\Library\site\lib"
        - perl -V:sitearch | findstr "/C:%PREFIX:\=/%\Library\site\lib"
        - perl -V:vendorlib | findstr "/C:%PREFIX:\=/%\Library\vendor\lib"
        - perl -V:vendorarch | findstr "/C:%PREFIX:\=/%\Library\vendor\lib"

about:
  homepage: http://www.perl.org/
  documentation: https://www.perl.org/docs.html
  repository: https://perl5.git.perl.org/perl.git
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - if: unix
      then:
        - Artistic
        - Copying
    - if: win
      then:
        - licenses/perl/Artistic
        - licenses/perl/Copying
  summary: The Perl programming language interpreter.
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
    - isuruf
    - mbargull
